=== SiarheiKulik/Practic/FourthTask/files/Task4xsd.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.training.by/classes"
        xmlns:tns="http://www.epam.training.by/classes"
        elementFormDefault="qualified">


    <element name="candies">
        <complexType>
            <sequence>
                <element name="candy" type="tns:Candy" minOccurs="1" maxOccurs="unbounded"></element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Candy">
        <sequence>
            <element name="name" type="string"/>
            <element name="energy" type="nonNegativeInteger"/>
            <element name="ingredients" type="tns:Ingredients"/>
            <element name="value" type="tns:Value"/>
            <element name="production" type="string"/>
        </sequence>
        <attribute name="id" type="tns:CandyId" use="required"/>
        <attribute name="type" type="tns:CandyType" use="required"/>
        <attribute type="string" name="topping" use="optional" />
    </complexType>

<simpleType name="CandyType">
            <restriction base="string">
            <enumeration value="caramel" />
            <enumeration value="chocolate" />
            <enumeration value="souffle" />
            </restriction>
    </simpleType>

    <complexType name="CaramelType">
        <complexContent>
            <extension base="tns:Candy"/>
        </complexContent>
    </complexType>

    <complexType name="ChocolateType">
        <complexContent>
            <extension base="tns:Candy">
            </extension>
        </complexContent>
    </complexType>

    <complexType name="SouffleType">
        <complexContent>
            <extension base="tns:Candy"/>
        </complexContent>
    </complexType>


    <simpleType name="CandyId">
        <restriction base="ID">
            <pattern value="([a-zA-Z])[\d]{2,5}"/>
        </restriction>
    </simpleType>

    <complexType name="Ingredients">
        <sequence>
            <element name="water">
                <simpleType>
                    <restriction base="nonNegativeInteger">
                        <maxInclusive value="1000" />
                    </restriction>
                </simpleType>
            </element>
            <element name="sugar" type="nonNegativeInteger"/>
            <element name="fructose" type="nonNegativeInteger"/>
            <element name="vanilla" type="nonNegativeInteger"/>
            <element name="chocolatetype" minOccurs="0">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="white" />
                        <enumeration value="milk" />
                        <enumeration value="dark" />
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>

    <complexType name="Value">
        <sequence>
            <element name="proteins" type="nonNegativeInteger"/>
            <element name="fats" type="nonNegativeInteger"/>
            <element name="carbohydrates" type="nonNegativeInteger"/>
        </sequence>
    </complexType>

    <element name="candy" type="tns:Candy" abstract="true"></element>
    <element name="caramel" type="tns:CaramelType" substitutionGroup="tns:candy"/>
    <element name="chocolate" type="tns:ChocolateType" substitutionGroup="tns:candy"/>
    <element name="souffle" type="tns:SouffleType" substitutionGroup="tns:candy"/>

</schema>

=== SiarheiKulik/Practic/FourthTask/files/Task4.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.epam.training.by/classes"
         xsi:schemaLocation="Task4xsd.xsd">

    <candy id="c1000" type="chocolate">
        <name>Stolichnye</name>
        <energy>10</energy>
        <ingredients>
            <water>10</water>
            <sugar>45</sugar>
            <fructose>0</fructose>
            <vanilla>5</vanilla>
            <chocolatetype>dark</chocolatetype>
        </ingredients>
        <value>
            <proteins>4</proteins>
            <fats>0</fats>
            <carbohydrates>20</carbohydrates>
        </value>
        <production>Komunarka</production>
    </candy>

    <candy id="c1001" type="caramel">
        <name>Barbaris</name>
        <energy>10</energy>
        <ingredients>
            <water>10</water>
            <sugar>50</sugar>
            <fructose>0</fructose>
            <vanilla>0</vanilla>
        </ingredients>
        <value>
            <proteins>3</proteins>
            <fats>0</fats>
            <carbohydrates>15</carbohydrates>
        </value>
        <production>Spartak</production>
    </candy>

    <candy id="c1002" type="caramel">
        <name>Key</name>
        <energy>15</energy>
        <ingredients>
            <water>200</water>
            <sugar>0</sugar>
            <fructose>50</fructose>
            <vanilla>10</vanilla>
        </ingredients>
        <value>
            <proteins>10</proteins>
            <fats>10</fats>
            <carbohydrates>20</carbohydrates>
        </value>
        <production>Kommunarka</production>
    </candy>

    <candy id="c1003" type="chocolate" topping="coconut crisp">
        <name>Alyonka</name>
        <energy>40</energy>
        <ingredients>
            <water>40</water>
            <sugar>70</sugar>
            <fructose>0</fructose>
            <vanilla>5</vanilla>
            <chocolatetype>milk</chocolatetype>
        </ingredients>
        <value>
            <proteins>20</proteins>
            <fats>10</fats>
            <carbohydrates>40</carbohydrates>
        </value>
        <production>Spartak</production>
    </candy>

    <candy id="c1004" type="souffle">
        <name>Aeroflot</name>
        <energy>40</energy>
        <ingredients>
            <water>45</water>
            <sugar>80</sugar>
            <fructose>0</fructose>
            <vanilla>5</vanilla>
        </ingredients>
        <value>
            <proteins>20</proteins>
            <fats>5</fats>
            <carbohydrates>50</carbohydrates>
        </value>
        <production>Kommunarka</production>
    </candy>
</candies>
